routes/web.php
<?php

use App\Http\Controllers\RewardsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');

/* About */
Route::group(['prefix' => 'about', 'as' => 'about.'], function() {

    Route::get('/', function() {
        return view('about.about');
    })->name('index');

    /* Organizations */
    Route::group(['prefix' => 'organization', 'as' => 'org.'], function() {
        Route::get('jpcs-apc', function() {
            return view('about.jpcs');
        })->name('jpcs');
        Route::get('jissa-apc', function() {
            return view('about.jissa');
        })->name('jissa');
        Route::get('apc-msc', function() {
            return view('about.msc');
        })->name('msc');
        Route::get('gaming-genesis', function() {
            return view('about.gaming-genesis');
        })->name('gaming-genesis');
    });
});

/* Policies */
Route::group(['prefix' => 'policies', 'as' => 'policy.'], function() {

    /* Privacy Policy */
    Route::get('privacy-policy', function() {
       return view('policy.privacy');
    })->name('privacy');

});

Route::middleware('auth')->get('dashboard', function() {
   return redirect()->route('dashboard.index');
});

/* Leaderboards */
Route::get('leaderboard', function() {
    return view('dashboard.leaderboard');
})->name('leaderboard');

/* Accounts */
Route::group(['prefix' => 'account', 'middleware' => ['auth']], function() {

    /* Dashboard */
    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function() {

        Route::get('/', [DashboardController::class, 'index'])->name('index');
    });

    /* Profile */
    Route::group(['as' => 'account.'], function() {

        Route::get('/', function() {
           return redirect()->route('account.index');
        });

        Route::get('me', [AccountController::class, 'index'])->name('index');
    });

});

/* Admin */
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => [
        'auth',
        'can:role:create|role:read|role:update|role:delete',
    ]
], function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');

    /* Roles */
    Route::group(['prefix' => 'roles', 'as' => 'roles.'], function() {
        Route::get('/', [AdminController::class, 'viewRoles'])->name('index');
        Route::get('{role}', [AdminController::class, 'viewRole'])->name('view');
    });

    /* Rewards */
    Route::group(['prefix' => 'rewards', 'as' => 'rewards.'], function() {
       Route::get('/', [RewardsController::class, 'index'])->name('index');
    });
});

Route::get('/test', function () {
   return url()->previous();
});

Route::middleware('auth')->get('user/points', [DashboardController::class, 'getCurrentUserPoints']);

require __DIR__.'/auth.php';

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Reward;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        $rewards = Reward::all();

        return view('dashboard.dashboard', compact('rewards'));
    }

    public function validateCode(Request $request)
    {
        if($request->code === '3v3nt') {
            return http_response_code(200);
        } else {
            abort('404', 'Event code is not valid.');
        }
    }
}

app/View/Components/AboutLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AboutLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.about');
    }
}

resources/views/dashboard/dashboard.blade.php
<x-about-layout>
    <x-page-header>
        <section id="dashboard" class="font-poppins">
            <span class="h-16 w-16 rounded-xl bg-gradient-to-br flex items-center justify-center from-[#5e60ce] to-[#6930c3] text-white mb-8">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 21v-4m0 0V5a2 2 0 012-2h6.5l1 1H21l-3 6 3 6h-8.5l-1-1H5a2 2 0 00-2 2zm9-13.5V9" />
                </svg>
            </span>
            <p class="text-3xl sm:text-5xl lg:text-6xl leading-none font-extrabold text-white tracking-tight mb-8">Points Tracker</p>
        </section>
    </x-page-header>
    <div class="relative pt-8 px-8 md:px-16">
        <div class="max-w-screen-lg xl:max-w-screen-xl mx-auto transition-all" x-data="codeForm()">
            @livewire('point-tracker')
            @can(['rewards:read', 'rewards:redeem'])
                <div class="grid xl:grid-cols-2 gap-4 sm:pt-6 transition-all text-white">
                    @foreach($rewards as $reward)
                        @livewire('reward-card', ['reward' => $reward])
                    @endforeach
                </div>
            @else
                <div class="relative text-center sm:pt-6 transition-all text-white">
                    <span class="font-bold">You are not allowed to view rewards.</span>
                </div>
            @endcannot
        </div>
    </div>

    @can(['rewards:read', 'rewards:redeem'])
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
            'apiToken' => $currentUser->api_token ?? null,
        ]) !!};
    </script>

    <script>
        function codeForm() {
            return {
                async codeInput() {
                    const { value: eventCode } = await Swal.fire({
                        title: 'Enter event code',
                        input: 'text',
                        inputValue: '',
                        showCancelButton: true,
                        showLoaderOnConfirm: true,
                        confirmButtonText: 'Submit',
                        inputValidator: (value) => {
                            if (!value) {
                                return 'You need to write something!'
                            }
                        },
                    })

                    if (eventCode) {
                        return livewire.emit('codeSubmitted', eventCode);
                    }
                },
            }
        }

        document.addEventListener('DOMContentLoaded', () => {
            this.livewire.on('code:error', code => {
                Swal.fire({
                    icon: 'error',
                    title: 'No such code',
                    html: 'Reward not found with code <strong>' + code + '</strong>',
                })
            });

            this.livewire.on('code:success', reward => {
                Swal.fire({
                    icon: 'success',
                    title: 'Reward claimed successfully',
                    html: '<strong>' + reward + '</strong>',
                })
            });

            this.livewire.on('code:exists', reward => {
                Swal.fire({
                    icon: 'error',
                    title: 'Reward already claimed',
                    html: '<strong>' + reward + '</strong>',
                })
            });
        });
    </script>
    @endcanany
</x-about-layout>

resources/views/dashboard/leaderboard.blade.php
<x-about-layout>
    <x-page-header>
        <section id="leaderboard" class="font-poppins">
            <span class="h-16 w-16 rounded-xl bg-gradient-to-br flex items-center justify-center from-[#5e60ce] to-[#6930c3] text-white mb-8">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 21v-4m0 0V5a2 2 0 012-2h6.5l1 1H21l-3 6 3 6h-8.5l-1-1H5a2 2 0 00-2 2zm9-13.5V9" />
                </svg>
            </span>
            <p class="text-3xl sm:text-5xl lg:text-6xl leading-none font-extrabold text-white tracking-tight mb-8">Leaderboard</p>
        </section>
    </x-page-header>
    <div class="relative pt-8 px-8 md:px-16">
        <div class="max-w-screen-lg xl:max-w-screen-xl mx-auto">
            <livewire:leaderboard/>
        </div>
    </div>
</x-about-layout>